[2024-04-13 17:45:00] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 17:45:05] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 17:45:07] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 905d54621bd8d9e7 [::1]:41288 failed checkpoint posthandshake: Connected to self
[2024-04-13 17:45:07] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn 905d54621bd8d9e7 [::1]:20136 failed checkpoint posthandshake: Connected to self
[2024-04-13 17:45:10] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 17:45:15] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 17:45:20] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 17:45:25] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 17:45:30] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 17:45:35] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 17:45:39] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn 905d54621bd8d9e7 [::1]:20136 failed checkpoint posthandshake: Connected to self
[2024-04-13 17:45:39] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 905d54621bd8d9e7 [::1]:56582 failed checkpoint posthandshake: Connected to self
[2024-04-13 17:45:40] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 17:45:45] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 17:45:50] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 17:45:55] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
