[2024-04-13 18:49:04] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-04-13 18:49:09] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-04-13 18:49:14] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-04-13 18:49:14] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 2680fb919c17c10a [::1]:32984 failed checkpoint posthandshake: Connected to self
[2024-04-13 18:49:14] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn 2680fb919c17c10a [::1]:20132 failed checkpoint posthandshake: Connected to self
[2024-04-13 18:49:19] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-04-13 18:49:24] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-04-13 18:49:29] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-04-13 18:49:34] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-04-13 18:49:39] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-04-13 18:49:44] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-04-13 18:49:46] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 2680fb919c17c10a [::1]:41744 failed checkpoint posthandshake: Connected to self
[2024-04-13 18:49:46] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn 2680fb919c17c10a [::1]:20132 failed checkpoint posthandshake: Connected to self
[2024-04-13 18:49:49] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-04-13 18:49:54] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-04-13 18:49:59] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
