[2024-04-13 16:39:04] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:39:09] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:39:14] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:39:14] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 2680fb919c17c10a [::1]:56036 failed checkpoint posthandshake: Connected to self
[2024-04-13 16:39:14] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn 2680fb919c17c10a [::1]:20132 failed checkpoint posthandshake: Connected to self
[2024-04-13 16:39:19] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:39:24] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:39:29] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:39:34] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:39:39] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:39:44] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:39:46] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 2680fb919c17c10a [::1]:47470 failed checkpoint posthandshake: Connected to self
[2024-04-13 16:39:46] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn 2680fb919c17c10a [::1]:20132 failed checkpoint posthandshake: Connected to self
[2024-04-13 16:39:49] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:39:54] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:39:59] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
