[2024-04-13 15:43:08] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 3023af312ae4d24d [::1]:52976 failed checkpoint posthandshake: Connected to self
[2024-04-13 15:43:08] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn 3023af312ae4d24d [::1]:20134 failed checkpoint posthandshake: Connected to self
[2024-04-13 15:43:08] [warning] server.go:553 p3Chain/p2p/server.(*Server).encHandshakeChecks 进行加密handshake: 节点已经与本机建立了连接

[2024-04-13 15:43:08] [warning] server.go:651 p3Chain/p2p/server.(*Server).setupConn inbound conn 21c561939067af2d [::1]:52970 failed checkpoint addpeer: Already connected
[2024-04-13 15:43:08] [warning] peer.go:166 p3Chain/p2p/server.(*Peer).run Peer 21c561939067af2d [::1]:20133: remote requested disconnect: Already connected

[2024-04-13 15:43:08] [warning] peer.go:207 p3Chain/p2p/server.(*Peer).pingLoop heart beate, ping协程退出

[2024-04-13 15:43:08] [warning] synchronization.go:175 p3Chain/blockSync.(*SyncProtocal).handle Block synchronization failed: Protocal handshake with node (21c561939067af2d03eaa74bcbb6ea8e2f311e5f27d1b98afb5d7a7426a0ead0ecb893269c2a70282ed8ac3bebe65bd3b84720dd16398c657f8b8312745cf84f) is failed, err:EOF

[2024-04-13 15:43:08] [warning] peer.go:316 p3Chain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2024-04-13 15:43:08] [warning] whisper.go:226 p3Chain/p2p/whisper.(*Whisper).handlePeer 无法发送whisper初始化消息,err:EOF

[2024-04-13 15:43:08] [warning] separator.go:128 p3Chain/core/separator.(*Separator).handlePeer separator: 协议handshake失败,err:EOF

[2024-04-13 15:43:08] [warning] peer.go:316 p3Chain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2024-04-13 15:43:08] [warning] peer.go:316 p3Chain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2024-04-13 15:43:39] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:43:39] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 3023af312ae4d24d [::1]:34312 failed checkpoint posthandshake: Connected to self
[2024-04-13 15:43:39] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn 3023af312ae4d24d [::1]:20134 failed checkpoint posthandshake: Connected to self
[2024-04-13 15:43:44] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:43:49] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:43:54] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:43:59] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
