[2024-04-13 15:45:04] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:45:09] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:45:14] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 3023af312ae4d24d [::1]:58352 failed checkpoint posthandshake: Connected to self
[2024-04-13 15:45:14] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn 3023af312ae4d24d [::1]:20134 failed checkpoint posthandshake: Connected to self
[2024-04-13 15:45:14] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:45:19] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:45:24] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:45:29] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:45:34] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:45:39] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:45:44] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:45:44] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 3023af312ae4d24d [::1]:42724 failed checkpoint posthandshake: Connected to self
[2024-04-13 15:45:44] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn 3023af312ae4d24d [::1]:20134 failed checkpoint posthandshake: Connected to self
[2024-04-13 15:45:49] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:45:54] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:45:59] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
