[2024-04-13 15:43:08] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 21c561939067af2d [::1]:38358 failed checkpoint posthandshake: Connected to self
[2024-04-13 15:43:08] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn 21c561939067af2d [::1]:20133 failed checkpoint posthandshake: Connected to self
[2024-04-13 15:43:08] [warning] server.go:553 p3Chain/p2p/server.(*Server).encHandshakeChecks 进行加密handshake: 节点已经与本机建立了连接

[2024-04-13 15:43:08] [warning] server.go:651 p3Chain/p2p/server.(*Server).setupConn inbound conn 3023af312ae4d24d [::1]:38360 failed checkpoint addpeer: Already connected
[2024-04-13 15:43:08] [warning] peer.go:166 p3Chain/p2p/server.(*Peer).run Peer 3023af312ae4d24d [::1]:20134: remote requested disconnect: Already connected

[2024-04-13 15:43:08] [warning] peer.go:207 p3Chain/p2p/server.(*Peer).pingLoop heart beate, ping协程退出

[2024-04-13 15:43:08] [warning] whisper.go:226 p3Chain/p2p/whisper.(*Whisper).handlePeer 无法发送whisper初始化消息,err:EOF

[2024-04-13 15:43:08] [warning] peer.go:316 p3Chain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2024-04-13 15:43:08] [warning] synchronization.go:175 p3Chain/blockSync.(*SyncProtocal).handle Block synchronization failed: Protocal handshake with node (3023af312ae4d24d15f997fffef54307be14c106eefe632597fc019223aaf84abb34c70ae6a30b04f1f3d6d97a27e93e9b33b9c251917f793c04641e42d28c11) is failed, err:EOF

[2024-04-13 15:43:08] [warning] peer.go:316 p3Chain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2024-04-13 15:43:08] [warning] separator.go:128 p3Chain/core/separator.(*Separator).handlePeer separator: 协议handshake失败,err:EOF

[2024-04-13 15:43:08] [warning] peer.go:316 p3Chain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2024-04-13 15:43:39] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 21c561939067af2d [::1]:50712 failed checkpoint posthandshake: Connected to self
[2024-04-13 15:43:39] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn 21c561939067af2d [::1]:20133 failed checkpoint posthandshake: Connected to self
[2024-04-13 15:43:40] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:43:45] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:43:50] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:43:55] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
