[2024-04-13 15:43:08] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 8b5bdccbc92a810e [::1]:59366 failed checkpoint posthandshake: Connected to self
[2024-04-13 15:43:08] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn 8b5bdccbc92a810e [::1]:20135 failed checkpoint posthandshake: Connected to self
[2024-04-13 15:43:38] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 8b5bdccbc92a810e [::1]:47184 failed checkpoint posthandshake: Connected to self
[2024-04-13 15:43:38] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn 8b5bdccbc92a810e [::1]:20135 failed checkpoint posthandshake: Connected to self
[2024-04-13 15:43:40] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:43:45] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:43:50] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:43:55] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
